[package]
name = "isitafox"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = {  version="1.0.202" , features=["derive"]}
serde_json = "1.0.117"
axum= { version="0.7.5", features=["multipart"]}
tokio= { version="1.0", features=["full"] }
rand = "0.8.5"
tch = "0.16.0"
minijinja = "2.0.1"